<?php

namespace App\Http\Controllers\Api\v1;

use App\Http\Controllers\Controller;
use App\Jobs\SendMerchantCallbackJob;
use App\Models\Transaction;
use App\Models\WebhookLog;
use App\Services\PaymentGateway\PaymentGatewayManager;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Throwable;

class WebhookController extends Controller
{
    public function __construct(protected PaymentGatewayManager $gatewayManager) {}

    /**
     * Handle Midtrans Webhook.
     */
    public function midtrans(Request $request): JsonResponse
    {
        return $this->processWebhook($request, 'midtrans', function (array $payload) {
            return $payload['order_id'] ?? null;
        });
    }

    /**
     * Handle Tripay Webhook.
     *
     * Processes transaction status updates sent by TriPay.
     *
     * @header X-Callback-Event string required The callback event name. Must be 'payment_status'. Example: payment_status
     * @header X-Callback-Signature string required The HMAC-SHA256 signature generated by TriPay. Example: 8e999526a8acf03f162d28381dd1eadd2f2974461713c437d85b428366d317f1
     */
    public function tripay(Request $request): JsonResponse
    {
        // Tripay sends validation on callback event (case-insensitive and trimmed for robustness)
        $event = $request->header('X-Callback-Event') ?: $request->header('x-callback-event');
        
        if (trim(strtolower($event ?? '')) !== 'payment_status') {
            Log::warning('Tripay webhook rejected: unrecognized event header.', [
                'received_event' => $event,
                'headers' => $request->headers->all(),
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Unrecognized callback event.',
            ], 400);
        }

        return $this->processWebhook($request, 'tripay', function (array $payload) {
            return $payload['merchant_ref'] ?? null;
        });
    }

    /**
     * Handle Tokopay Webhook.
     */
    public function tokopay(Request $request): JsonResponse
    {
        return $this->processWebhook($request, 'tokopay', function (array $payload) {
            return $payload['reff_id'] ?? null;
        });
    }

    /**
     * Handle Xendit Webhook.
     */
    public function xendit(Request $request): JsonResponse
    {
        return $this->processWebhook($request, 'xendit', function (array $payload) {
            return $payload['external_id'] ?? null;
        });
    }

    /**
     * Core Webhook processing logic.
     */
    protected function processWebhook(Request $request, string $gatewayCode, callable $extractRefId): JsonResponse
    {
        $payload = $request->json()->all();

        // 1. Log the incoming webhook (raw payload)
        $incomingLog = WebhookLog::create([
            'direction' => 'incoming',
            'payload' => $payload,
            'status_code' => 200,
            'notes' => 'Raw callback received from '.ucfirst($gatewayCode),
        ]);

        try {
            // 2. Extract reference ID
            $referenceId = $extractRefId($payload);

            if (empty($referenceId)) {
                $incomingLog->update([
                    'status_code' => 400,
                    'notes' => 'Reference ID could not be extracted from payload.',
                ]);

                return response()->json(['success' => false, 'message' => 'Invalid payload: missing reference ID.'], 400);
            }

            // 3. Find transaction
            $transaction = Transaction::where('reference_id', $referenceId)->first();

            if (! $transaction) {
                $incomingLog->update([
                    'status_code' => 404,
                    'notes' => "Transaction reference [{$referenceId}] not found in database.",
                ]);

                // Return success to gateway so it stops retrying for invalid local transactions
                return response()->json(['success' => true, 'message' => 'Transaction not found. No action taken.']);
            }

            // Associate log with transaction
            $incomingLog->update(['transaction_id' => $transaction->id]);

            // 4. Acquire Lock to prevent Race Conditions / Double Webhooks
            $lockKey = 'webhook_lock_'.$transaction->reference_id;
            $lock = Cache::lock($lockKey, 10);

            $status = $lock->block(5, function () use ($transaction, $payload, $request) {
                return DB::transaction(function () use ($transaction, $payload, $request) {
                    $transaction->refresh();

                    $gateway = $transaction->paymentMethod->gateway;
                    $driver = $this->gatewayManager->driver($gateway);

                    // Collect headers for driver signature verification if required
                    $headers = [
                        'x-callback-signature' => $request->header('x-callback-signature'),
                        'x-callback-token' => $request->header('x-callback-token'),
                        'raw_body' => $request->getContent(),
                    ];

                    // Verify signature and map status
                    $statusResponse = $driver->handleWebhook($payload, $headers);

                    $newPgStatus = $payload['transaction_status'] ?? $payload['status'] ?? $statusResponse->status;

                    // If status changes from PENDING, or pg_status changes, update and queue merchant callback
                    if ($transaction->status !== $statusResponse->status || $transaction->pg_status !== $newPgStatus) {
                        $oldStatus = $transaction->status;

                        $transaction->update([
                            'status' => $statusResponse->status,
                            'paid_at' => $statusResponse->paidAt,
                            'pg_ref_id' => $statusResponse->pgRefId ?? $transaction->pg_ref_id,
                            'pg_status' => $newPgStatus,
                            'pg_response' => array_merge($transaction->pg_response ?? [], [
                                'webhook' => $statusResponse->rawResponse,
                            ]),
                        ]);

                        SendMerchantCallbackJob::dispatch($transaction);
                    }

                    return true;
                });
            });

            if (! $status) {
                throw new \Exception('Failed to acquire transaction lock.');
            }

            // Standardize return responses for each gateway if needed
            if ($gatewayCode === 'tokopay') {
                return response()->json(['status' => 'true']);
            }

            return response()->json(['success' => true]);

        } catch (Throwable $e) {
            Log::error("Error processing webhook for {$gatewayCode}", [
                'payload' => $payload,
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);

            $incomingLog->update([
                'status_code' => 500,
                'notes' => 'Webhook processing failed: '.$e->getMessage(),
            ]);

            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
            ], 500);
        }
    }
}
